algorithm: FedCCFA
client_num: 100
sample_ratio: 0.2
seed: 0
device: cuda

dataset: CIFAR10
partition: hetero
alpha: 0.5
drift_pattern: false

model: CNN
rounds: 200
rep_epochs: 5
clf_epochs: 1
balanced_epochs: 5
momentum: 0.9
weight_decay: 0.00001
batch_size: 64
rep_lr: 0.01
clf_lr: 0.1
p_lr: 0.01
balanced_clf_lr: 0.1

lambda: 0.0
gamma: 20.0
penalize: CL
temperature: 0.1

eps: 0.1  # epsilon (maximum distance between two samples) in DBSCAN
oracle: false
num_classes: 10
weights: uniform
clustered_protos: true