algorithm: Flash
client_num: 100
sample_ratio: 0.2
seed: 0
device: cuda

dataset: CIFAR10
partition: hetero
alpha: 0.5
drift_pattern: false

model: CNN
rounds: 200
epochs: 5
momentum: 0.9
weight_decay: 0.00001
batch_size: 64
lr: 0.01
server_lr: 0.01
loss_decrement: 0.004
beta1: 0.9
beta2: 0.99
tau: 0.001
